// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: warehouse.proto

package warehouse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WareHouseDB_SetValue_FullMethodName    = "/warehouse.WareHouseDB/SetValue"
	WareHouseDB_GetValue_FullMethodName    = "/warehouse.WareHouseDB/GetValue"
	WareHouseDB_DeleteValue_FullMethodName = "/warehouse.WareHouseDB/DeleteValue"
)

// WareHouseDBClient is the client API for WareHouseDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WareHouseDBClient interface {
	SetValue(ctx context.Context, in *Pair, opts ...grpc.CallOption) (*Result, error)
	GetValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error)
	DeleteValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error)
}

type wareHouseDBClient struct {
	cc grpc.ClientConnInterface
}

func NewWareHouseDBClient(cc grpc.ClientConnInterface) WareHouseDBClient {
	return &wareHouseDBClient{cc}
}

func (c *wareHouseDBClient) SetValue(ctx context.Context, in *Pair, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, WareHouseDB_SetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wareHouseDBClient) GetValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, WareHouseDB_GetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wareHouseDBClient) DeleteValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, WareHouseDB_DeleteValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WareHouseDBServer is the server API for WareHouseDB service.
// All implementations must embed UnimplementedWareHouseDBServer
// for forward compatibility
type WareHouseDBServer interface {
	SetValue(context.Context, *Pair) (*Result, error)
	GetValue(context.Context, *Key) (*Result, error)
	DeleteValue(context.Context, *Key) (*Result, error)
	mustEmbedUnimplementedWareHouseDBServer()
}

// UnimplementedWareHouseDBServer must be embedded to have forward compatible implementations.
type UnimplementedWareHouseDBServer struct {
}

func (UnimplementedWareHouseDBServer) SetValue(context.Context, *Pair) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedWareHouseDBServer) GetValue(context.Context, *Key) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedWareHouseDBServer) DeleteValue(context.Context, *Key) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteValue not implemented")
}
func (UnimplementedWareHouseDBServer) mustEmbedUnimplementedWareHouseDBServer() {}

// UnsafeWareHouseDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WareHouseDBServer will
// result in compilation errors.
type UnsafeWareHouseDBServer interface {
	mustEmbedUnimplementedWareHouseDBServer()
}

func RegisterWareHouseDBServer(s grpc.ServiceRegistrar, srv WareHouseDBServer) {
	s.RegisterService(&WareHouseDB_ServiceDesc, srv)
}

func _WareHouseDB_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WareHouseDBServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WareHouseDB_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WareHouseDBServer).SetValue(ctx, req.(*Pair))
	}
	return interceptor(ctx, in, info, handler)
}

func _WareHouseDB_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WareHouseDBServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WareHouseDB_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WareHouseDBServer).GetValue(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _WareHouseDB_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WareHouseDBServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WareHouseDB_DeleteValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WareHouseDBServer).DeleteValue(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

// WareHouseDB_ServiceDesc is the grpc.ServiceDesc for WareHouseDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WareHouseDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.WareHouseDB",
	HandlerType: (*WareHouseDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValue",
			Handler:    _WareHouseDB_SetValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _WareHouseDB_GetValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _WareHouseDB_DeleteValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warehouse.proto",
}
